### ISSUE TITLE
[SPEF] Moteur de recherche tkinter

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/sandbox-python#8]
## Contexte

L'API Isogeo en lecture permet d'effectuer des recherches filtrées dans les inventaires de métadonnées des clients. 
Son utilisation requiert des compétences en développement.

## Objectifs

1. Créer une interface graphique permettant d'utiliser l'API sans avoir de compétences de développement. 

2. Valoriser le package [isogeo-pysdk](https://github.com/isogeo/isogeo-api-py-minsdk) en proposant une application concrète.

## Description

L'interface se lance à partir d'un script Python (3.7) qui doit fonctionner au moins sous Windows 10. Elle permet de filtrer les métadonnées accessibles selon différents champs et de savoir combien correspondent à la sélection.

### Authentification 

Le script Python doit être stocké dans un dossier contenant un fichier json d'authentification Isogeo  intitulé "client_secrets.json".

### Champs de filtre 

Les champs de filtre correspondent à certains filtres sémantiques permettant d’exécuter une recherche via l'API Isogeo (voir la [doc de l'API](http://help.isogeo.com/api/fr/methods/filtering.html)). On peut filtrer les métadonnées en fonction de :

* Mots-clefs associés 
* Groupe de travail
* Type de ressource 
* Format source
* Fournisseur

### Interface de filtre 

Les champs ne possèdent pas le même nombre d'entrées ce qui implique d'utiliser deux interfaces de sélection différentes :
*  Barre de recherche à autocomplétion pour la sélection des Mots-clefs.
*  Menu déroulant de sélection pour les autres champs.

Au lancement du script, l'interface apparaît et une requête est effectuée via l'API Isogeo pour obtenir les modalités des champs de filtre et ajouter les options dont dispose l'utilisateur aux widgets de sélection. 

### Récupération et affichage du résultat
 
Quand l'utilisateur a effectué sa sélection, il lui reste à cliquer sur un bouton qui lance la requête permettant de connaître le nombre de métadonnées correspondantes. Cette requête est générée à partir de la combinaison des options sélectionnées dans les différents champs de filtre. Le nombre de métadonnées filtrées est extrait du résultat de la requête et affiché dans l'interface.

### Spécifications techniques

* La version 3.7 de Python est utilisée.
* La version 2.20.5 du package isogeo-pysdk est utilisée.
* Le package tkinter est utilisé pour générer l'interface afin de minimiser les dépendances externes.

## Objectifs optionnels

1.  **Asynchronie** : L'affichage du résultat doit s'actualiser en temps réel  et apparaître rapidement. De plus, les modalités des champs de sélection doivent également s'actualiser en fonction des options choisies dans les autres champs. 

2. **Authentification dynamique** : Plutôt que de demander à l'utilisateur de stocker le script au même endroit que son fichier json d'authentification, il doit pouvoir accéder à ce fichier via l'interface, quelque soient son emplacement et son intitulé.

**Comment by SimonSAMPERE** [comment]
## Étapes identifiées : 

### Graphique
- [x] Conception/dessin de l'interface graphique #10
- [x] Implémentation de l'interface conçue #11
- [x] Remplir un widget depuis une requête de l'API #12
- [x] Formater les sorties destinés aux requêtes #13
- [x] Gérer la synchronisation des champs pour éviter les combinaisons vides #14

### Requête  
- [x] Lister les types de requêtes nécessaires #15
- [x] Les implémenter (entrées, sorties, automatisme, nombre/format des entrées/sorties) #16


### Authentification
- [ ] Charger le fichier et récupérer le *token* #17

**Comment by Guts** [comment]
Exemple du résultat attendu :

![image](https://user-images.githubusercontent.com/1596222/55894637-be85df80-5bba-11e9-94d0-528345975836.png)

**Comment by SimonSAMPERE** [comment]
La conception de l'interface utilisateur (#10 ) a conduit à ré-envisager une des spécifications concernant le filtre des métadonnées. 
Pour filtrer en fonction des **mots-clef, le menu déroulant** est préféré (comme pour les autres champs) à la barre de recherche à autocomplétion qui implique un développement asynchrone ne relevant pas des objectifs prioritaires.
